version: '3'
networks:
  traefik_traefik: 
    external: true

services:
  sqnotes:
    build: .
    image: sqnotes
    volumes:
      - ./data:/app/data
    restart: always
      #ports:
      #- 8080:8080
    labels:
      - "traefik.http.routers.gitea.rule=Host(`notes.sq.lan`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_traefik"
    networks:
      traefik_traefik:
