version: '3'
networks:
  traefik_traefik: 
    external: true

services:
  sqnotes:
    build: .
    image: sqnotes
    volumes:
      - ./data:/app/data
    restart: always
      #ports:
      #- 8080:8080
    labels:
      - "traefik.http.routers.sqnotes.rule=Host(`notes.squi.fr`)"
      - "traefik.http.services.sqnotes.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_traefik"
    networks:
      traefik_traefik:
